# hosts/whio-vm/default.nix
{
  pkgs
  , specialArgs
  , ...
}:
let
  # Destructure 'hostname' from the specialArgs passed from flake.nix
  inherit (specialArgs) hostname username;
in
{

  imports = [
    # Host specific configuration
    ./hardware-configuration.nix
    ./persistence.nix                         # Preservation configuration

    # Basic configuration
    ../../lib/nixos/base-packages.nix
    ../../lib/nixos/base-security.nix
    ../../lib/nixos/flatpak.nix
    ../../lib/nixos/hardware-services.nix
    ../../lib/nixos/hyprland-services.nix
    ../../lib/nixos/multimedia.nix
    ../../lib/nixos/zram.nix
    ../../lib/nixos/snapper.nix
    ../../lib/nixos/nvidia.nix
  ];

  hardware.cpu.amd.updateMicrocode = true;

  boot = {
    blacklistedKernelModules = [ "nouveau" ];
    kernelParams = [ "amd.iommu=on" ];
  };

  environment.systemPackages = with pkgs; [
    xdg-desktop-portal
    xdg-desktop-portal-gtk
    impala
  ];

  # Time and locale are specific to the physical location
  time.timeZone = "Pacific/Auckland";
  i18n.defaultLocale = "en_NZ.UTF-8";
  
  networking = {
    hostName = hostname;
    networkmanager.enable = true;
    wireless.iwd.enable = true;
  };

  services = {
    # Input
    libinput.enable = true;
    # Hardware
    udev.enable = true;
    power-profiles-daemon.enable = true;
    blueman.enable = true; # Bluetooth
    # Printing
    printing.enable = true;
    # Discovery
    avahi.enable = true;
  };

  users = {
    users.${username} = {
      home = "/home/${username}";
      isNormalUser = true;
      # Add host-specific groups. This list is merged with 'wheel' from configuration.nix.
      extraGroups = [ "wheel" "users" "video" username ];
      # generated by `mkpasswd -m scrypt --rounds=11`
      initialHashedPassword = "$7$GU..../....S9EPW0eEM5JL4uh1Bo1yr/$bDP2HRn7G8LV8jLV2yj3DQHJJPE0svzRh0Q2fEPePN9";
    };
    users.root.initialHashedPassword = "$7$GU..../....S9EPW0eEM5JL4uh1Bo1yr/$bDP2HRn7G8LV8jLV2yj3DQHJJPE0svzRh0Q2fEPePN9";
  };

}
