# ./hosts/whio/default.nix
{
  specialArgs,
  ...
}:
let
  inherit (specialArgs) hostname username;
in
{

  imports = [
    #+----- Host specific configuration ----------
    ./hardware-configuration.nix
    ./persistence.nix # Preservation configuration

    #+----- Basic configuration ------------------
    ../../lib/nixos/base-packages.nix
    ../../lib/nixos/base-security.nix
    ../../lib/nixos/btrfs.nix
    ../../lib/nixos/maintenance.nix
    ../../lib/nixos/virt.nix
    ../../lib/nixos/incus.nix # Incus virtualization
    ../../lib/nixos/zram.nix
  ];

  hardware.cpu.amd.updateMicrocode = true;
  hardware.enableRedistributableFirmware = true;
  hardware.ksm.enable = true;

  boot = {
    kernel.sysctl = {
      "vfs_cache_pressure" = 50;
      "vm.swappiness" = 10;
      "vm.dirty_background_ratio" = 5;
      "vm.dirty_ratio"= 10;
    };
    kernelParams = [
      "amd.iommu=on"
      # "transparent_hugepage=madvise" # NixOS sets madvise by default (25.11) cat /sys/kernel/mm/transparent_hugepage/enabled always [madvise] never
    ];

    # Configure LUKS auto-unlock with keyfile
    initrd.luks.devices.crypted = {
      device = "/dev/disk/by-uuid/UUID_OF_LUKS_PARTITION"; # IMPORTANT: REPLACE THIS WITH ACTUAL LUKS PARTITION UUID (e.g., from blkid or lsblk -f)
      keyFile = "/secret.key";
    };
    initrd.extraFiles."/secret.key" = {
      source = "/boot/secret.key"; # Source path on the unencrypted /boot partition
      mode = "0400"; # Restrict permissions for the keyfile
    };
    initrd.extraFiles."/mnt/luks-backup-key/tahi-luks-backup.key" = {
      source = "/mnt/luks-backup-key/tahi-luks-backup.key"; # Source path on the mounted USB partition
      mode = "0400"; # Restrict permissions for the keyfile
    };
  };

  # Time and locale are specific to the physical location
  time.timeZone = "Pacific/Auckland";
  i18n.defaultLocale = "en_NZ.UTF-8";

  networking = {
    hostName = hostname;
    # wireless.iwd.enable = true; # Not needed for a server
  };

  services = {
    avahi.enable = true; # Discovery
    # blueman.enable = true; # Bluetooth - Not needed for a server
    # libinput.enable = true; # Input - Not needed for a server
    # printing.enable = true; # Printing - Not needed for a server
    resolved.enable = true; # DNS
    udev.enable = true; # Hardware

    # Enable OpenSSH daemon for remote access
    openssh = {
      enable = true;
      permitRootLogin = lib.mkForce "prohibit-password"; # Allow root login only with keys
      passwordAuthentication = false;
      settings = {
        # Add your SSH public key here for passwordless access
        # For initial setup, you might manually add it to /root/.ssh/authorized_keys
        # or use home-manager to deploy it for non-root users.
      };
    };
  };

  users = {
    users.${username} = {
      home = "/home/${username}";
      isNormalUser = true;
      extraGroups = [
        "input"
        "network"
        "users"
        "video"
        "wheel"
        username
      ];
      # generated by `mkpasswd -m scrypt --rounds=11`
      initialHashedPassword = "$7$GU..../....S9EPW0eEM5JL4uh1Bo1yr/$bDP2HRn7G8LV8jLV2yj3DQHJJPE0svzRh0Q2fEPePN9";
    };
    users.root.initialHashedPassword = "$7$GU..../....S9EPW0eEM5JL4uh1Bo1yr/$bDP2HRn7G8LV8jLV2yj3DQHJJPE0svzRh0Q2fEPePN9";
  };

}
