# ./hosts/whio/default.nix
{
  specialArgs
  , ...
}:
let
  inherit (specialArgs) hostname username;
in
{

  imports = [
    #+----- Host specific configuration ----------
    ./hardware-configuration.nix
    ./persistence.nix # Preservation configuration

    #+----- Basic configuration ------------------
    ../../lib/nixos/asus.nix
    ../../lib/nixos/base-packages.nix
    ../../lib/nixos/btrfs.nix
    ../../lib/nixos/base-security.nix
    ../../lib/nixos/docker.nix
    ../../lib/nixos/flatpak.nix
    ../../lib/nixos/gaming.nix
    ../../lib/nixos/hardware-services.nix
    ../../lib/nixos/hyprland-services.nix
    ../../lib/nixos/maintenance.nix
    ../../lib/nixos/multimedia.nix
    ../../lib/nixos/nvidia.nix
    ../../lib/nixos/secureboot.nix
    ../../lib/nixos/snapper.nix
    ../../lib/nixos/xdg.nix
    ../../lib/nixos/virt.nix
    ../../lib/nixos/zram.nix
  ];

  hardware.cpu.amd.updateMicrocode = true;
  hardware.enableRedistributableFirmware = true;
  hardware.ksm.enable = true;

  boot = {
    blacklistedKernelModules = [ "nouveau" ];
    kernel.sysctl = {
      "vfs_cache_pressure" = 50;
      "vm.swappiness" = 10;
      "vm.dirty_background_ratio" = 5;
      "vm.dirty_ratio"= 10;
    };
    kernelParams = [
      "amd.iommu=on"
      # "transparent_hugepage=madvise" # NixOS sets madvise by default (25.11) cat /sys/kernel/mm/transparent_hugepage/enabled always [madvise] never
    ];
  };

  # Time and locale are specific to the physical location
  time.timeZone = "Pacific/Auckland";
  i18n.defaultLocale = "en_NZ.UTF-8";

  networking = {
    hostName = hostname;
    wireless.iwd.enable = true;
  };

  services = {
    avahi.enable = true; # Discovery
    blueman.enable = true; # Bluetooth
    libinput.enable = true; # Input
    printing.enable = true; # Printing
    resolved.enable = true; # DNS
    udev.enable = true; # Hardware
  };

  users = {
    users.${username} = {
      home = "/home/${username}";
      isNormalUser = true;
      extraGroups = [
        "input"
        "network"
        "users"
        "video"
        "wheel"
        username
      ];
      # generated by `mkpasswd -m scrypt --rounds=11`
      initialHashedPassword = "$7$GU..../....S9EPW0eEM5JL4uh1Bo1yr/$bDP2HRn7G8LV8jLV2yj3DQHJJPE0svzRh0Q2fEPePN9";
    };
    users.root.initialHashedPassword = "$7$GU..../....S9EPW0eEM5JL4uh1Bo1yr/$bDP2HRn7G8LV8jLV2yj3DQHJJPE0svzRh0Q2fEPePN9";
  };

}
