# ./hosts/tahi/default.nix
{
  lib,
  specialArgs,
  ...
}:
let
  inherit (specialArgs) hostname username;
in
{

  imports = [
    #+----- Host specific configuration ----------
    ./hardware-configuration.nix
    ./persistence.nix # Preservation configuration

    #+----- Basic configuration ------------------
    ../../lib/nixos/base-packages.nix
    ../../lib/nixos/base-security.nix
    ../../lib/nixos/btrfs.nix
    ../../lib/nixos/maintenance.nix
    ../../lib/nixos/virt.nix
    ../../lib/nixos/incus.nix # Incus virtualization
    ../../lib/nixos/zram.nix
  ];

  hardware.cpu.amd.updateMicrocode = true;
  hardware.enableRedistributableFirmware = true;
  hardware.ksm.enable = true;

  boot = {
    kernel.sysctl = {
      "vfs_cache_pressure" = 50;
      "vm.swappiness" = 10;
      "vm.dirty_background_ratio" = 5;
      "vm.dirty_ratio"= 10;
    };
  };

  # Time and locale are specific to the physical location
  time.timeZone = "Pacific/Auckland";
  i18n.defaultLocale = "en_NZ.UTF-8";

  networking = {
    bridges."br0".interfaces = [ "enp2s0f0" ];
    defaultGateway = "172.16.1.1";
    nameservers = [
      "1.1.1.1"
      "8.8.8.8"
    ];
    firewall.trustedInterfaces = [ "br0" ];
    hostName = hostname;
    interfaces = {
      br0 = {
        ipv4.addresses = [
          {
            address = "172.16.1.30";
            prefixLength = 24;
          }
        ];
        useDHCP = false;
      };
      enp2s0f0.useDHCP = false;
    };
    nftables.enable = true;
    useDHCP = false;
  };

  services = {
    avahi.enable = true; # Discovery
    resolved.enable = true; # DNS
    udev.enable = true; # Hardware

    # Enable OpenSSH daemon for remote access
    openssh = {
      enable = true;
      settings = {
        PermitRootLogin = lib.mkForce "prohibit-password"; # Allow root login only with keys
        PasswordAuthentication = false;
        # Add your SSH public key here for passwordless access
        # For initial setup, you might manually add it to /root/.ssh/authorized_keys
        # or use home-manager to deploy it for non-root users.
      };
    };
  };

  systemd.tmpfiles.rules = [
    "z /etc/ssh/ssh_host_ed25519_key 0640 root keys - -"
  ];

  users = {
    users.${username} = {
      home = "/home/${username}";
      isNormalUser = true;
      extraGroups = [
        "input"
        "keys"
        "network"
        "users"
        "video"
        "wheel"
        username
      ];
      # generated by `mkpasswd -m scrypt --rounds=11`
      initialHashedPassword = "$7$GU..../....S9EPW0eEM5JL4uh1Bo1yr/$bDP2HRn7G8LV8jLV2yj3DQHJJPE0svzRh0Q2fEPePN9";
      openssh.authorizedKeys.keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFJCkeOcvLsmdbtI/gkuqGSB5XQYLaLdF74M3Ck2vPuQ rhys@whio"
      ];
    };
    users.root.initialHashedPassword = "$7$GU..../....S9EPW0eEM5JL4uh1Bo1yr/$bDP2HRn7G8LV8jLV2yj3DQHJJPE0svzRh0Q2fEPePN9";
  };

}
