{
  nixpkgs
  , pkgs
  , username
  , ...
}:
let
  # generated by `mkpasswd -m scrypt --rounds=11`
  hash = "$7$GU..../....q5xEsuaY12NlWgPXS/HZg.$Xq2EM6RK2OM0Bon4TOxHAtlfV8MHv3KxKf1GBHG/4G7";
in
{

# -------------------------------------------------------------------------
# CORE ENVIRONMENT
# -------------------------------------------------------------------------
# Time and Locale settings moved to host-specific files

  console = {
    keyMap = "us";
  };

  environment = {
    systemPackages = with pkgs; [
      curl
      git
      vim
      wget
    ];
    variables.EDITOR = "vim";
  };

  programs.nano.enable = false;

  users = {
    mutableUsers = false;

    users.${username} = {
      initialHashedPassword = hash;
    };

    users.root = {
      initialHashedPassword = hash;
    };
  };

}
