{
  nixpkgs
  , pkgs
  , username
  , ...
}:
let
  # generated by `mkpasswd -m scrypt --rounds=11`
in
{

  nix = {
    settings = {
      accept-flake-config = true;
      experimental-features = [ "nix-command" "flakes" ];
      # Add the user to the trusted list for better performance
      trusted-users = [ username "@wheel" ];
      substituters = [
        "https://cache.nixos.org"
      ];
    };

  };

  nixpkgs.config.allowUnfree = true;

# -------------------------------------------------------------------------
# CORE ENVIRONMENT
# -------------------------------------------------------------------------
# Time and Locale settings moved to host-specific files

  console = {
    keyMap = "us";
  };

  environment = {
    systemPackages = with pkgs; [
      curl
      git
      vim
      wget
    ];
    variables.EDITOR = "vim";
  };

  programs.nano.enable = false;

  users = {

    users.${username} = {
      # generated by `mkpasswd -m scrypt --rounds=11`
      initialHashedPassword = "$7$GU..../....S9EPW0eEM5JL4uh1Bo1yr/$bDP2HRn7G8LV8jLV2yj3DQHJJPE0svzRh0Q2fEPePN9";
    };

    users.root = {
      # generated by `mkpasswd -m scrypt --rounds=11`
      initialHashedPassword = "$7$GU..../....S9EPW0eEM5JL4uh1Bo1yr/$bDP2HRn7G8LV8jLV2yj3DQHJJPE0svzRh0Q2fEPePN9";
    };
  };

}
